name: CI

on:
  create:
    branches: 
      - release/**
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'dotnet/dotnet.sln'
      BUILD_VERSION: '1.0.0'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$BUILD_VERSION --no-restore

    - name: Run tests
      run: dotnet test $SOLUTION --no-restore --no-build --verbosity normal
      
    - name: Publish
      if: startsWith(github.ref, 'refs/heads/master')
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}
